version: '3.1'

services:
  node:
    image: node:lts-alpine3.17
    command: sh -c "sleep infinity"
    working_dir: /workspace/project
    volumes:
      - ../project:/workspace/project:delegated
    ports:
      - "5173:5173"
